In [37]:
import pandas as pd 
df1 = pd.DataFrame({'A':[1,2,3,4],'B':['hello','how','are','you']})
df1

A      B
0  1  hello
1  2    how
2  3    are
3  4    you

In [38]:
df1=pd.read_csv(r"C:/Users/User/Downloads/DatasetForCoffeeSales2.csv")
print(df1)

           Date  Customer_ID    City      Category     Product  Unit Price  \
0      1/1/2023           32  Riyadh  coffee beans   Colombian          40   
1      1/2/2023           49    Abha  coffee beans  Costa Rica          35   
2      1/3/2023           75   Tabuk  coffee beans  Costa Rica          35   
3      1/4/2023           80    Abha  coffee beans   Ethiopian          45   
4      1/5/2023           78    Hail  coffee beans   Colombian          40   
..          ...          ...     ...           ...         ...         ...   
725  12/26/2024            4    Hail  coffee beans   Colombian          40   
726  12/27/2024           63   Mecca  coffee beans   Colombian          40   
727  12/28/2024           39    Abha  coffee beans  Costa Rica          35   
728  12/29/2024           57   Tabuk  coffee beans   Ethiopian          45   
729  12/30/2024           50  Medina  coffee beans   Brazilian          30   

     Quantity  Sales Amount  Used_Discount  Discount_Amount  Fi

In [39]:
df1.head()

Date  Customer_ID    City      Category     Product  Unit Price  \
0  1/1/2023           32  Riyadh  coffee beans   Colombian          40   
1  1/2/2023           49    Abha  coffee beans  Costa Rica          35   
2  1/3/2023           75   Tabuk  coffee beans  Costa Rica          35   
3  1/4/2023           80    Abha  coffee beans   Ethiopian          45   
4  1/5/2023           78    Hail  coffee beans   Colombian          40   

   Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
0        14           560          False                0          560  
1        17           595          False                0          595  
2        19           665          False                0          665  
3         1            45          False                0           45  
4        46          1840           True              368         1472

In [40]:
df1.head(10)

Date  Customer_ID      City      Category     Product  Unit Price  \
0   1/1/2023           32    Riyadh  coffee beans   Colombian          40   
1   1/2/2023           49      Abha  coffee beans  Costa Rica          35   
2   1/3/2023           75     Tabuk  coffee beans  Costa Rica          35   
3   1/4/2023           80      Abha  coffee beans   Ethiopian          45   
4   1/5/2023           78      Hail  coffee beans   Colombian          40   
5   1/6/2023            1    Khobar  coffee beans   Colombian          40   
6   1/7/2023           95  Buraidah  coffee beans   Brazilian          30   
7   1/8/2023           27    Medina  coffee beans   Colombian          40   
8   1/9/2023           73      Hail  coffee beans   Guatemala          35   
9  1/10/2023           82    Dammam  coffee beans  Costa Rica          35   

   Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
0        14           560          False                0          560  
1        17           595          False                0          595  
2        19           665          False                0          665  
3         1            45          False                0           45  
4        46          1840           True              368         1472  
5        32          1280           True              256         1024  
6         1            30           True                6           24  
7        33          1320          False                0         1320  
8        47          1645          False                0         1645  
9         4           140          False                0          140

In [41]:
df1.tail()

Date  Customer_ID    City      Category     Product  Unit Price  \
725  12/26/2024            4    Hail  coffee beans   Colombian          40   
726  12/27/2024           63   Mecca  coffee beans   Colombian          40   
727  12/28/2024           39    Abha  coffee beans  Costa Rica          35   
728  12/29/2024           57   Tabuk  coffee beans   Ethiopian          45   
729  12/30/2024           50  Medina  coffee beans   Brazilian          30   

     Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
725        26          1040          False                0         1040  
726        10           400          False                0          400  
727        47          1645          False                0         1645  
728         3           135           True               27          108  
729        33           990           True              198          792

In [42]:
df1.tail(10)

Date  Customer_ID    City      Category     Product  Unit Price  \
720  12/21/2024           22  Jeddah  coffee beans  Costa Rica          35   
721  12/22/2024           72  Khobar  coffee beans   Colombian          40   
722  12/23/2024           83  Jeddah  coffee beans   Brazilian          30   
723  12/24/2024           49    Abha  coffee beans   Brazilian          30   
724  12/25/2024           20    Hail  coffee beans  Costa Rica          35   
725  12/26/2024            4    Hail  coffee beans   Colombian          40   
726  12/27/2024           63   Mecca  coffee beans   Colombian          40   
727  12/28/2024           39    Abha  coffee beans  Costa Rica          35   
728  12/29/2024           57   Tabuk  coffee beans   Ethiopian          45   
729  12/30/2024           50  Medina  coffee beans   Brazilian          30   

     Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
720        15           525           True              105          420  
721        43          1720           True              344         1376  
722         4           120          False                0          120  
723        28           840          False                0          840  
724        46          1610          False                0         1610  
725        26          1040          False                0         1040  
726        10           400          False                0          400  
727        47          1645          False                0         1645  
728         3           135           True               27          108  
729        33           990           True              198          792

In [43]:
df1.iloc[1:5]

Date  Customer_ID   City      Category     Product  Unit Price  \
1  1/2/2023           49   Abha  coffee beans  Costa Rica          35   
2  1/3/2023           75  Tabuk  coffee beans  Costa Rica          35   
3  1/4/2023           80   Abha  coffee beans   Ethiopian          45   
4  1/5/2023           78   Hail  coffee beans   Colombian          40   

   Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
1        17           595          False                0          595  
2        19           665          False                0          665  
3         1            45          False                0           45  
4        46          1840           True              368         1472

In [44]:
df1.describe()

Customer_ID  Unit Price    Quantity  Sales Amount  Discount_Amount  \
count   730.000000  730.000000  730.000000    730.000000       730.000000   
mean     51.669863   36.794521   26.080822    959.924658        97.393151   
std      29.014339    4.955104   14.480971    551.282730       123.401350   
min       1.000000   30.000000    1.000000     30.000000         0.000000   
25%      27.250000   35.000000   14.000000    495.000000         0.000000   
50%      52.000000   35.000000   27.000000    960.000000        13.000000   
75%      77.000000   40.000000   39.000000   1400.000000       192.000000   
max     100.000000   45.000000   49.000000   2205.000000       441.000000   

       Final Sales  
count   730.000000  
mean    862.531507  
std     509.032315  
min      24.000000  
25%     448.000000  
50%     840.000000  
75%    1260.000000  
max    2205.000000

In [45]:
df1.dtypes

Date               object
Customer_ID         int64
City               object
Category           object
Product            object
Unit Price          int64
Quantity            int64
Sales Amount        int64
Used_Discount        bool
Discount_Amount     int64
Final Sales         int64
dtype: object

In [46]:
df1.isnull().sum()

Date               0
Customer_ID        0
City               0
Category           0
Product            0
Unit Price         0
Quantity           0
Sales Amount       0
Used_Discount      0
Discount_Amount    0
Final Sales        0
dtype: int64

In [47]:
df1['Product'][1:5]

1    Costa Rica
2    Costa Rica
3     Ethiopian
4     Colombian
Name: Product, dtype: object

In [48]:
df1.dtypes

Date               object
Customer_ID         int64
City               object
Category           object
Product            object
Unit Price          int64
Quantity            int64
Sales Amount        int64
Used_Discount        bool
Discount_Amount     int64
Final Sales         int64
dtype: object

In [49]:
df1.columns

Index(['Date', 'Customer_ID', 'City', 'Category', 'Product', 'Unit Price',
       'Quantity', 'Sales Amount', 'Used_Discount', 'Discount_Amount',
       'Final Sales'],
      dtype='object')

In [50]:
df1=df1.rename(columns={'City':'Markets'})
df1

Date  Customer_ID Markets      Category     Product  Unit Price  \
0      1/1/2023           32  Riyadh  coffee beans   Colombian          40   
1      1/2/2023           49    Abha  coffee beans  Costa Rica          35   
2      1/3/2023           75   Tabuk  coffee beans  Costa Rica          35   
3      1/4/2023           80    Abha  coffee beans   Ethiopian          45   
4      1/5/2023           78    Hail  coffee beans   Colombian          40   
..          ...          ...     ...           ...         ...         ...   
725  12/26/2024            4    Hail  coffee beans   Colombian          40   
726  12/27/2024           63   Mecca  coffee beans   Colombian          40   
727  12/28/2024           39    Abha  coffee beans  Costa Rica          35   
728  12/29/2024           57   Tabuk  coffee beans   Ethiopian          45   
729  12/30/2024           50  Medina  coffee beans   Brazilian          30   

     Quantity  Sales Amount  Used_Discount  Discount_Amount  Final Sales  
0          14           560          False                0          560  
1          17           595          False                0          595  
2          19           665          False                0          665  
3           1            45          False                0           45  
4          46          1840           True              368         1472  
..        ...           ...            ...              ...          ...  
725        26          1040          False                0         1040  
726        10           400          False                0          400  
727        47          1645          False                0         1645  
728         3           135           True               27          108  
729        33           990           True              198          792  

[730 rows x 11 columns]

In [51]:
df1['Product'][1:50:2]

1     Costa Rica
3      Ethiopian
5      Colombian
7      Colombian
9     Costa Rica
11     Brazilian
13    Costa Rica
15     Ethiopian
17     Colombian
19     Ethiopian
21     Brazilian
23     Colombian
25    Costa Rica
27    Costa Rica
29     Guatemala
31    Costa Rica
33     Colombian
35     Brazilian
37     Colombian
39     Brazilian
41     Colombian
43     Colombian
45     Brazilian
47     Guatemala
49     Brazilian
Name: Product, dtype: object

In [52]:
df1.dtypes


Date               object
Customer_ID         int64
Markets            object
Category           object
Product            object
Unit Price          int64
Quantity            int64
Sales Amount        int64
Used_Discount        bool
Discount_Amount     int64
Final Sales         int64
dtype: object

In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


In [56]:
arr= np.arange(5 , 10)
print(arr)


[5 6 7 8 9]


In [57]:
arr = np.zeros(5)
print(arr)


[0. 0. 0. 0. 0.]


In [59]:
a=[6,4,3,6,5,7,9]
d=np.unique(a)
print(d)

[3 4 5 6 7 9]
